spring:
  application:
    name: object-relational
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:postgresql://localhost:5432/bdwas?currentSchema=object-relational
    username: bdwas
    password: bdwas

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        format_sql: true
        default_schema: object-relational


server:
  port: 8083
