spring:
  application:
    name: relational
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:postgresql://localhost:5432/bdwas?currentSchema=relational
    username: bdwas
    password: bdwas

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        format_sql: true
        default_schema: relational
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        #generate_statistics: true

server:
  port: 8080
