spring:
  application:
    name: object

  jpa:
    hibernate:
        ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20000
        order_inserts: true
        order_updates: true

server:
  port: 8082
